import { Row } from "react-table";

export const demoData = [
  {
    id: 38,
    category: null,
    notes: [
      { type: "paragraph", children: [{ text: "" }] },
      {
        type: "image",
        url: "http://0.0.0.0:8000/assets/09-roll-safe.w700.h700_dNk0S8C.jpg",
        children: [{ text: "" }],
      },
    ],
    tasks: [
      {
        id: 20,
        category: null,
        notes: [{ type: "paragraph", children: [{ text: "" }] }],
        created: "2021-03-17",
        modified: "2021-03-17",
        name: "Test",
        description: "Testing",
        due_date: null,
        completed: false,
        completed_on: null,
        assigned_to: null,
        template: null,
        assets: [],
      },
    ],
    created: "2021-03-17",
    modified: "2021-03-17",
    name: "Real Template",
    description: ".",
    due_date: "2021-03-04",
    is_recurring: false,
    repeat_interval: null,
    repeat_interval_units: null,
    completed: false,
    completed_on: null,
    vessel: null,
    template: 3,
  },
  {
    id: 39,
    category: "Test Category",
    notes: [
      { type: "paragraph", children: [{ text: "This " }] },
      {
        type: "image",
        url: "/assets/09-roll-safe.w700.h700_6JjDobb.jpg",
        children: [{ text: "" }],
      },
      { type: "paragraph", children: [{ text: "is my note" }] },
    ],
    tasks: [
      {
        id: 21,
        category: "Test Category",
        notes: [{ type: "paragraph", children: [{ text: "test" }] }],
        created: "2021-03-17",
        modified: "2021-03-17",
        name: "Test3",
        description: ".",
        due_date: null,
        completed: false,
        completed_on: null,
        assigned_to: null,
        template: null,
        assets: [],
      },
      {
        id: 22,
        category: "Test Category",
        notes: [{ type: "paragraph", children: [{ text: "" }] }],
        created: "2021-03-17",
        modified: "2021-03-17",
        name: "Test4",
        description: "",
        due_date: null,
        completed: false,
        completed_on: null,
        assigned_to: null,
        template: null,
        assets: [],
      },
      {
        id: 23,
        category: null,
        notes: [{ type: "paragraph", children: [{ text: "" }] }],
        created: "2021-03-17",
        modified: "2021-03-17",
        name: "Test2",
        description: "",
        due_date: null,
        completed: false,
        completed_on: null,
        assigned_to: null,
        template: null,
        assets: [],
      },
    ],
    created: "2021-03-17",
    modified: "2021-04-15",
    name: "Test",
    description: "Testdasdasdf",
    due_date: "2021-03-11",
    is_recurring: false,
    repeat_interval: 3,
    repeat_interval_units: "weeks",
    completed: true,
    completed_on: "2021-04-15",
    vessel: null,
    template: 2,
  },
  {
    id: 40,
    category: "Test Category",
    notes: [
      {
        type: "paragraph",
        children: [
          { text: "" },
          {
            type: "link",
            url: "http://example.com",
            children: [{ text: "This " }],
          },
          { text: "" },
        ],
      },
      {
        type: "image",
        url: "/assets/09-roll-safe.w700.h700_6JjDobb.jpg",
        children: [{ text: "" }],
      },
      { type: "paragraph", children: [{ text: "is my note" }] },
    ],
    tasks: [
      {
        id: 24,
        category: "Test Category",
        notes: [{ type: "paragraph", children: [{ text: "test" }] }],
        created: "2021-03-24",
        modified: "2021-03-24",
        name: "Test3",
        description: ".",
        due_date: null,
        completed: false,
        completed_on: null,
        assigned_to: null,
        template: null,
        assets: [],
      },
      {
        id: 25,
        category: "Test Category",
        notes: [{ type: "paragraph", children: [{ text: "" }] }],
        created: "2021-03-24",
        modified: "2021-03-24",
        name: "Test4",
        description: "",
        due_date: null,
        completed: false,
        completed_on: null,
        assigned_to: null,
        template: null,
        assets: [],
      },
      {
        id: 26,
        category: null,
        notes: [{ type: "paragraph", children: [{ text: "" }] }],
        created: "2021-03-24",
        modified: "2021-03-24",
        name: "Test2",
        description: "",
        due_date: null,
        completed: false,
        completed_on: null,
        assigned_to: null,
        template: null,
        assets: [],
      },
    ],
    created: "2021-03-24",
    modified: "2021-03-24",
    name: "Test",
    description: "Testdasdasdf",
    due_date: "2021-03-02",
    is_recurring: false,
    repeat_interval: 3,
    repeat_interval_units: "weeks",
    completed: false,
    completed_on: null,
    vessel: null,
    template: 2,
  },
  {
    id: 41,
    category: "Test Category",
    notes: [
      {
        type: "paragraph",
        children: [
          { text: "" },
          {
            type: "link",
            url: "http://example.com",
            children: [{ text: "This " }],
          },
          { text: "" },
        ],
      },
      {
        type: "image",
        url: "/assets/09-roll-safe.w700.h700_6JjDobb.jpg",
        children: [{ text: "" }],
      },
      { type: "paragraph", children: [{ text: "is my note" }] },
    ],
    tasks: [],
    created: "2021-03-28",
    modified: "2021-03-28",
    name: "Test",
    description: "Testdasdasdf",
    due_date: "2021-03-04",
    is_recurring: false,
    repeat_interval: 3,
    repeat_interval_units: "weeks",
    completed: false,
    completed_on: null,
    vessel: null,
    template: 2,
  },
  {
    id: 42,
    category: "Test Category",
    notes: [
      {
        type: "paragraph",
        children: [
          { text: "" },
          {
            type: "link",
            url: "http://example.com",
            children: [{ text: "This " }],
          },
          { text: "" },
        ],
      },
      {
        type: "image",
        url: "/assets/09-roll-safe.w700.h700_6JjDobb.jpg",
        children: [{ text: "" }],
      },
      { type: "paragraph", children: [{ text: "is my note" }] },
    ],
    tasks: [],
    created: "2021-03-28",
    modified: "2021-03-28",
    name: "Test",
    description: "Testdasdasdf",
    due_date: "2021-03-04",
    is_recurring: false,
    repeat_interval: 3,
    repeat_interval_units: "weeks",
    completed: false,
    completed_on: null,
    vessel: null,
    template: 2,
  },
  {
    id: 43,
    category: "Test Category",
    notes: [
      {
        type: "paragraph",
        children: [
          { text: "" },
          {
            type: "link",
            url: "http://example.com",
            children: [{ text: "This " }],
          },
          { text: "" },
        ],
      },
      {
        type: "image",
        url: "/assets/09-roll-safe.w700.h700_6JjDobb.jpg",
        children: [{ text: "" }],
      },
      { type: "paragraph", children: [{ text: "is my note" }] },
    ],
    tasks: [],
    created: "2021-03-28",
    modified: "2021-03-28",
    name: "Test",
    description: "Testdasdasdf",
    due_date: "2021-03-04",
    is_recurring: false,
    repeat_interval: 3,
    repeat_interval_units: "weeks",
    completed: false,
    completed_on: null,
    vessel: null,
    template: 2,
  },
  {
    id: 44,
    category: "Test Category",
    notes: [
      {
        type: "paragraph",
        children: [
          { text: "" },
          {
            type: "link",
            url: "http://example.com",
            children: [{ text: "This " }],
          },
          { text: "" },
        ],
      },
      {
        type: "image",
        url: "/assets/09-roll-safe.w700.h700_6JjDobb.jpg",
        children: [{ text: "" }],
      },
      { type: "paragraph", children: [{ text: "is my note" }] },
    ],
    tasks: [],
    created: "2021-03-28",
    modified: "2021-03-28",
    name: "Test",
    description: "Testdasdasdf",
    due_date: "2021-03-04",
    is_recurring: false,
    repeat_interval: 3,
    repeat_interval_units: "weeks",
    completed: false,
    completed_on: null,
    vessel: null,
    template: 2,
  },
];

export const demoColumns = [
  { accessor: "name", Header: "Name" },
  { accessor: "due_date", Header: "Due Date" },
  { accessor: "is_recurring", Header: "Recurring" },
  // {
  //   accessor: (row: Row) => {
  //     return `${row.repeat_interval || ""} ${row.repeat_interval_units || ""}`;
  //   },
  //   id: "repeat_interval_with_units",
  //   Header: "Repeat Interval",
  // },
  { accessor: "category", Header: "Category" },
];
